DROP TABLE IF EXISTS addOns;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS entry_types;
DROP TABLE IF EXISTS users;